<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PicoGK" Version="1.7.7.4" />
  </ItemGroup>

  <ItemGroup>
    <None Include="config\*.json" />
    <None Include="docs\**\*.md" />
    <None Include="*.sh" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="01_GettingStarted\**\*.cs" />
    <Compile Remove="FFSC-PicoGK\FFSC_PicoGK.TestRunner\**\*.cs" />
    <Compile Remove="GeometryII\**\*.cs" />
    <Compile Remove="EngineFFSC\**\*.cs" />
    <Compile Remove="rocket\**\*.cs" />
    <Compile Remove="analysis\**\*.cs" />
    <None Include="FFSC-PicoGK\**\*.json" />
    <None Include="FFSC-PicoGK\**\*.md" />
    <None Include="FFSC-PicoGK\**\*.sh" />
  </ItemGroup>

</Project>
